# Define the script name
SCRIPT=./turnupsecurityshield_cptools.sh

# Default target: Install
install:
	# Run the installation script
	bash $(SCRIPT)

# Uninstall target: Revert changes based on log file
uninstall:
	# Run the uninstall script
	bash ./uninstall.sh
